_BASE_: "Base-CenterNet2.yaml"
MODEL:
  BACKBONE:
    NAME: "build_vovnet_fpn_backbone"
    FREEZE_AT: 0
  WEIGHTS: "models/vovnet19_ese_slim_dw_detectron2.pth"
  VOVNET:
    OUT_FEATURES: [ "res2", "res3", "res4", "res5" ]
    CONV_BODY : "V-19-slim-dw-eSE"
  BIFPN:
    NUM_BIFPN: 3
    OUT_CHANNELS: 160

  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.12, 57.375]
  CENTERNET:
    USE_DEFORMABLE: True
  ROI_HEADS:
    IN_FEATURES: ["p3", "p4"]
TEST:
  EVAL_PERIOD: 1000
SOLVER:
  MAX_ITER: 140000
  CHECKPOINT_PERIOD: 7000
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BASE_LR: 0.01
  IMS_PER_BATCH: 2
INPUT:
  CUSTOM_AUG: EfficientDetResizeCrop
  TRAIN_SIZE: 640
  FORMAT: RGB

